### ISSUE TITLE
Compilation with urdfdom parser

### ISSUE THREAD

**Issue by Leph** [ipab-slmc/pinocchio_catkin#3]
Hi @wxmerkt,

On a fresh Kinetic + Ubuntu 16.04 environment, I need to pass the following compiler definition to achieve Pinocchio compilation:
`-DPINOCCHIO_URDFDOM_TYPEDEF_SHARED_PTR -DPINOCCHIO_WITH_URDFDOM`
in order to prevent the following error:
```
In file included from /data/WorkspaceUoE/install/include/pinocchio/parsers/urdf.hpp:11:0,
                 from /data/WorkspaceUoE/src/uoe_val_control/uoe_apps/test/testPinocchio.cpp:13:
/data/WorkspaceUoE/install/include/pinocchio/parsers/urdf/types.hpp:45:32: error: redefinition of ‘template<class T, class U> boost::shared_ptr<X> urdf::const_pointer_cast(const boost::shared_ptr<U>&)’
   PINOCCHIO_URDF_SHARED_PTR(T) const_pointer_cast(PINOCCHIO_URDF_SHARED_PTR(U) const & r)
```
See overview-urdf.cpp at https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/

I would suggest to add the following line to `cmake/pinocchio.cmake`:
`add_definitions(-DPINOCCHIO_URDFDOM_TYPEDEF_SHARED_PTR -DPINOCCHIO_WITH_URDFDOM)`

**Comment by wxmerkt** [comment]
Those should be auto-discovered automatically? No? Can you check the logic in pinocchio.cmake why it isnt?
